version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGDB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGDB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
